# Copyright 2020 Ververica GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2.1"
services:
  python_model:
    build: statefun-workshop-python
    ports:
    - "8888:8888"
  master:
    image: ververica/flink-statefun-training:1.0.0
    # uncomment build line to rebuild the image
    #build: .
    # uncomment and adjust savepoint path to start from a savepoint
    command: -s /savepoint-dir/savepoint-3df90d-aa82d691740f
    expose:
    - "6123"
    ports:
    - "8001:8001"
    environment:
    - ROLE=master
    - MASTER_HOST=master
    volumes:
    - ./savepoint-dir:/savepoint-dir
  worker:
    image: ververica/flink-statefun-training:1.0.0
    # uncomment build line to rebuild the image
    #build: .
    expose:
    - "6121"
    - "6122"
    - "6123"
    depends_on:
    - master
    - python_model
    links:
    - "master:master"
    environment:
    - ROLE=worker
    - MASTER_HOST=master
    volumes:
    - ./savepoint-dir:/savepoint-dir

